spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/naver_store?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ',Yu/tqye<7hr'
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60000
#    password: 123456
    jedis:
      pool:
        max-total: 100
        max-wait: 1000
        max-idle: 100
        min-idle: 50
        num-tests-per-eviction-run: 50
  mybatis-plus:
    type-aliases-package: com.example.spikesystem.entity # 给pojo实体类起别名
    mapper-locations: classpath:mapper/*.xml
server:
  port: 9090
  servlet:
    context-path: /spike
